name: server
version: 0.0.1
description: A simple console application.
dependencies:
  rethinkdb_driver: ^2.3.1
  # Version 1.0.4 has mysterious "pub get" spam about "drudge". If you update
  # this dependency, be sure not to include 1.0.4 and to check the output of
  # "pub get" for spam about "drudge".
  json_schema: 1.0.3